#!/bin/bash
#################################################################
#                                                               #
# Copyright (c) 2025 DnaSoft BV and/or its subsidiaries.        #
# All rights reserved.                                          #
#                                                               #
#   This source code contains the intellectual property         #
#   of its copyright holder(s), and is made available           #
#   under a license.  If you do not know the terms of           #
#   the license, please stop and do not read further.           #
#                                                               #
#################################################################

. /home/vehu/etc/env
export ydb_max_sockets=16384
export ydb_treat_sigusr2_like_sigusr1=1
export gtmroutines="/home/vehu/lib/gtm/plugin/o/_mind.so "$gtmroutines
yottadb -run %XCMD "do start^%mind(\"""$@\")"
