# MIND for YottaDB configuration file
#
# Warning: values set by this file can be overwritten by command line switches

# this will set a new listen port
port=10001

# this will change the log level. You can choose between: none,sessions,commands,responses
# log-level=sessions

# This will redirect the logging to a file
# log-file=/tmp/mind.log

# this will change the user commands directory
#uapi-dir=/home/vehu/lib/gtm/plugin/etc/mind/rvs

# this will switch the dump requests on or off
# dump-request=yes

# this will switch the dump responses on or off
# dump-response=yes

# this will change the way statistics are collected:
# off       no statistics at all
# grand     only collect the grand totals
# details   collect extended statistics
# statistics=grand

# this will change the way internal errors are displayed:
# none      does not display anything
# brief     display only the $zstatus
# extended  display the entire stack
# error-dump=extended

# this will change the protocol to UDS
# protocol=uds

# this will set the uds filename
# uds-file=testfile